### PR TITLE
Changed Bootstrap icons with handmade pixelart

### PR DESCRIPTION
**Pull request by sukhchainn**
I made two changes for now. Please let me know what you think about it.

### CODE REVIEW

**Comment by maujin111** [comment]
Please resolve the conflicts

**Comment by maujin111** [comment]
make sure everything is working, please. It seems like the download page is empty

**Comment by sukhchainn** [comment]
I don't know what's happening. I think GitHub is treating downloads.html file as a binary file and it says that binary file is corrupted. When I go to my fork then everything seems to be fine, the downloads.html file is as its supposed to be. Don't know why it's showing as empty here.

**Comment by sukhchainn** [comment]
I think it should be able to merge now. Doesn't seem to have any problem.

**Comment by Zughy** [comment]
Hey there, thanks for your contribution!
I can't load the current icons on Firefox so I was quite happy to actually see something, but these look a bit too amateur for a site to be accepted. The main reason is the wobbly effect they have, and one thing I suggest you (in general) to avoid that is to use [antialiasing](https://youtube.com/watch?v=UN-m3o9V7kk) ([privacy friendly link](https://yewtu.be/watch?v=UN-m3o9V7kk)), as it'll improve your drawings a lot. Especially when working with one single colour in a big format - yes, even silhouettes can be hard :D

**Pull request closed without merging**
