### PR TITLE
Revert "Revert "Website update""

### PR DESCRIPTION
**Pull request by MintStudios**
Reverts LibreSprite/libresprite.github.io#2

### CODE REVIEW

**Comment by maujin111** [comment]
Fix the link to the linux file

**Comment by akien-mga** [comment]
@MintStudios Please wait for peer review, what's this mess? https://github.com/LibreSprite/libresprite.github.io/commits/master

Why are there binary files in the Git repo?

**Comment by akien-mga** [comment]
If you want to host binaries, use GitHub Releases for that. Binary files in Git are a big no-go.

Don't revert PRs and revert reverts of PRs, it makes the Git history terribly messy. If you merged something which is *completely* wrong, then yeah, revert it, but ideally wait for reviews before merging things which are wrong. And if you merged something which is only partly wrong, make a PR to fix what needs to be fixed. Merge/revert is not do/undo, it leaves an indelible trace in the repo.

**Comment by maujin111** [comment]
sorry, would not happen again

**Comment by MintStudios** [comment]
Yeah, sorry about that.

**Comment by MintStudios** [comment]
I'm gonna go ahead and make master protected, make you admin, and me me maintainer.

**Comment by akien-mga** [comment]
Well no worry, this is a new repo and it's not as important as keeping things super clean over in @LibreSprite/LibreSprite. Sorry for my rant of grumpy old dev :)

But yeah I added the same policy on this repo as on LibreSprite, that each PR should have at least one review before being merged. There's no urgency after 4 years to get stuff done ASAP, so we can take a few hours to refine changes and merge good PRs.

**Pull request merged**
